### PR TITLE
Invoke print as a fuction for python3 support

### PR DESCRIPTION
**Pull request by poy**
Signed-off-by: Andrew Poydence <apoydence@pivotal.io>

### CODE REVIEW

**Comment by jasonkeene** [comment]
You can use `from __future__ import print_function` to make `print` behave the same on python2 and python3.

**Comment by poy** [comment]
@jasonkeene Is that a preferred pattern?

**Comment by jasonkeene** [comment]
Yeah, the `__future__` thing is the preferred way. Also, this had a lot of merge conflicts. You might want to try rewriting all the prints on `origin/master` if you want python3 support.

**Comment by poy** [comment]
This has been resolved.

**Pull request closed without merging**
